// Animals & Biology Flash Cards (Enhanced with Difficulty Levels)
export const animalsBiology = {
  id: 'animals-biology',
  name: 'Animals & Biology',
  description: 'Learn about animal classifications, biology terms, and famous naturalists',
  category: 'Science',
  cards: [
    // EASY - Most famous animal facts
    { id: 1, question: 'What is the largest animal in the world?', answer: 'Blue Whale', difficulty: 'easy' },
    { id: 2, question: 'What is the largest land animal?', answer: 'African Elephant', difficulty: 'easy' },
    { id: 3, question: 'What is the fastest land animal?', answer: 'Cheetah', difficulty: 'easy' },
    { id: 4, question: 'What is the tallest animal?', answer: 'Giraffe', difficulty: 'easy' },
    { id: 5, question: 'What is the only mammal that can fly?', answer: 'Bat', difficulty: 'easy' },
    { id: 6, question: 'What is the process by which plants make food using sunlight?', answer: 'Photosynthesis', difficulty: 'easy' },
    { id: 7, question: 'What is the basic unit of life?', answer: 'Cell', difficulty: 'easy' },
    { id: 8, question: 'What carries genetic information in cells?', answer: 'DNA (Deoxyribonucleic Acid)', difficulty: 'easy' },
    { id: 9, question: 'Who wrote "On the Origin of Species"?', answer: 'Charles Darwin', difficulty: 'easy' },
    { id: 10, question: 'Which naturalist studied finches in the Galápagos?', answer: 'Charles Darwin', difficulty: 'easy' },
    { id: 11, question: 'What is the largest bird that cannot fly?', answer: 'Ostrich', difficulty: 'easy' },
    { id: 12, question: 'What is the fastest bird in a dive?', answer: 'Peregrine Falcon', difficulty: 'easy' },
    { id: 13, question: 'What is winter sleep in animals called?', answer: 'Hibernation', difficulty: 'easy' },
    { id: 14, question: 'What is the world\'s largest rainforest?', answer: 'Amazon Rainforest', difficulty: 'easy' },
    { id: 15, question: 'What is the world\'s largest coral reef system?', answer: 'Great Barrier Reef', difficulty: 'easy' },
    
    // MEDIUM - Requires more detailed knowledge
    { id: 16, question: 'What is the largest primate?', answer: 'Gorilla', difficulty: 'medium' },
    { id: 17, question: 'What is the largest reptile?', answer: 'Saltwater Crocodile', difficulty: 'medium' },
    { id: 18, question: 'What is the smallest mammal?', answer: 'Bumblebee Bat', difficulty: 'medium' },
    { id: 19, question: 'What is a group of lions called?', answer: 'Pride', difficulty: 'medium' },
    { id: 20, question: 'What is a group of crows called?', answer: 'Murder', difficulty: 'medium' },
    { id: 21, question: 'What is a group of wolves called?', answer: 'Pack', difficulty: 'medium' },
    { id: 22, question: 'Which bear species is native to China and endangered?', answer: 'Giant Panda', difficulty: 'medium' },
    { id: 23, question: 'Which great ape shares 98% of human DNA?', answer: 'Chimpanzee', difficulty: 'medium' },
    { id: 24, question: 'What is the powerhouse of the cell?', answer: 'Mitochondria', difficulty: 'medium' },
    { id: 25, question: 'What is the process of cell division?', answer: 'Mitosis', difficulty: 'medium' },
    { id: 26, question: 'What is the study of heredity?', answer: 'Genetics', difficulty: 'medium' },
    { id: 27, question: 'What is the green pigment in plants?', answer: 'Chlorophyll', difficulty: 'medium' },
    { id: 28, question: 'What is the largest organ in the human body?', answer: 'Skin', difficulty: 'medium' },
    { id: 29, question: 'What is the hardest substance in the human body?', answer: 'Tooth Enamel', difficulty: 'medium' },
    { id: 30, question: 'How many bones are in the adult human body?', answer: '206', difficulty: 'medium' },
    { id: 31, question: 'Who studied chimpanzees in Tanzania?', answer: 'Jane Goodall', difficulty: 'medium' },
    { id: 32, question: 'Which primatologist studied gorillas in Rwanda?', answer: 'Dian Fossey', difficulty: 'medium' },
    { id: 33, question: 'Who is known for the documentary series "Planet Earth"?', answer: 'David Attenborough', difficulty: 'medium' },
    { id: 34, question: 'What ecosystem has trees that lose leaves seasonally?', answer: 'Deciduous Forest', difficulty: 'medium' },
    { id: 35, question: 'What biome is characterized by permafrost?', answer: 'Tundra', difficulty: 'medium' },
    
    // HARD - Obscure biology and animal facts
    { id: 36, question: 'What is a group of fish called?', answer: 'School', difficulty: 'hard' },
    { id: 37, question: 'What is a group of whales called?', answer: 'Pod', difficulty: 'hard' },
    { id: 38, question: 'What is a group of geese called?', answer: 'Gaggle (on ground) or Skein (in flight)', difficulty: 'hard' },
    { id: 39, question: 'What is a group of elephants called?', answer: 'Herd', difficulty: 'hard' },
    { id: 40, question: 'What is a baby kangaroo called?', answer: 'Joey', difficulty: 'hard' },
    { id: 41, question: 'What is a baby swan called?', answer: 'Cygnet', difficulty: 'hard' },
    { id: 42, question: 'What is a baby horse called?', answer: 'Foal', difficulty: 'hard' },
    { id: 43, question: 'Which Asian big cat is critically endangered?', answer: 'Siberian Tiger', difficulty: 'hard' },
    { id: 44, question: 'Which African rhino species has two subspecies?', answer: 'Black Rhinoceros', difficulty: 'hard' },
    { id: 45, question: 'Which marine mammal is extinct in China\'s Yangtze River?', answer: 'Baiji (Yangtze River Dolphin)', difficulty: 'hard' },
    { id: 46, question: 'Who was the "Crocodile Hunter"?', answer: 'Steve Irwin', difficulty: 'hard' },
    { id: 47, question: 'Which Swedish botanist created the system of naming species?', answer: 'Carl Linnaeus', difficulty: 'hard' },
    { id: 48, question: 'What is the world\'s largest desert?', answer: 'Antarctic Desert (or Sahara for hot desert)', difficulty: 'hard' },
    { id: 49, question: 'What ecosystem is dominated by grasses?', answer: 'Grassland (or Savanna)', difficulty: 'hard' },
    { id: 50, question: 'What is the ability to change color to match surroundings?', answer: 'Camouflage', difficulty: 'hard' },
    { id: 51, question: 'What is the scientific name for humans?', answer: 'Homo sapiens', difficulty: 'hard' },
    { id: 52, question: 'What is the largest living structure on Earth?', answer: 'Great Barrier Reef', difficulty: 'hard' },
    { id: 53, question: 'What mammal has the longest gestation period?', answer: 'African Elephant (22 months)', difficulty: 'hard' },
    { id: 54, question: 'What bird lays the largest eggs?', answer: 'Ostrich', difficulty: 'hard' },
    { id: 55, question: 'What is the only continent without native reptiles?', answer: 'Antarctica', difficulty: 'hard' },
    { id: 56, question: 'What animal has the longest lifespan?', answer: 'Greenland Shark or Ocean Quahog Clam', difficulty: 'hard' },
    { id: 57, question: 'What is the smallest bird in the world?', answer: 'Bee Hummingbird', difficulty: 'hard' },
    { id: 58, question: 'What mammal has the most powerful bite?', answer: 'Hippopotamus', difficulty: 'hard' },
    { id: 59, question: 'What is the loudest animal on Earth?', answer: 'Blue Whale', difficulty: 'hard' },
    { id: 60, question: 'What animal can survive in space?', answer: 'Tardigrade (Water Bear)', difficulty: 'hard' },
  ]
};

export default animalsBiology;
