// Bible Flash Cards (Enhanced with Difficulty Levels)
export const bible = {
  id: 'bible',
  name: 'The Bible',
  description: 'Learn biblical books, figures, stories, and locations',
  category: 'Arts & Culture',
  cards: [
    // EASY - Most famous stories and figures
    { id: 1, question: 'Who built an ark to survive the great flood?', answer: 'Noah', difficulty: 'easy' },
    { id: 2, question: 'Who led the Israelites out of Egypt?', answer: 'Moses', difficulty: 'easy' },
    { id: 3, question: 'Who killed the giant Goliath with a sling?', answer: 'David', difficulty: 'easy' },
    { id: 4, question: 'What is the first book of the Bible?', answer: 'Genesis', difficulty: 'easy' },
    { id: 5, question: 'What is the last book of the Bible?', answer: 'Revelation', difficulty: 'easy' },
    { id: 6, question: 'Where was Jesus born?', answer: 'Bethlehem', difficulty: 'easy' },
    { id: 7, question: 'Who betrayed Jesus for 30 pieces of silver?', answer: 'Judas Iscariot', difficulty: 'easy' },
    { id: 8, question: 'Who was the mother of Jesus?', answer: 'Mary', difficulty: 'easy' },
    { id: 9, question: 'Who denied Jesus three times before the rooster crowed?', answer: 'Peter', difficulty: 'easy' },
    { id: 10, question: 'Who was swallowed by a great fish?', answer: 'Jonah', difficulty: 'easy' },
    { id: 11, question: 'Who was the first man created by God?', answer: 'Adam', difficulty: 'easy' },
    { id: 12, question: 'In which garden did Adam and Eve live?', answer: 'Garden of Eden', difficulty: 'easy' },
    { id: 13, question: 'How many disciples did Jesus have?', answer: 'Twelve (12)', difficulty: 'easy' },
    { id: 14, question: 'Who parted the Red Sea?', answer: 'Moses', difficulty: 'easy' },
    { id: 15, question: 'What was Jesus\'s first miracle?', answer: 'Turning water into wine', difficulty: 'easy' },
    { id: 16, question: 'Who was sold into slavery by his brothers?', answer: 'Joseph', difficulty: 'easy' },
    { id: 17, question: 'Who baptized Jesus in the Jordan River?', answer: 'John the Baptist', difficulty: 'easy' },
    { id: 18, question: 'Who was asked by God to sacrifice his son Isaac?', answer: 'Abraham', difficulty: 'easy' },
    { id: 19, question: 'How many commandments did Moses receive?', answer: 'Ten (10)', difficulty: 'easy' },
    { id: 20, question: 'Where was Jesus crucified?', answer: 'Golgotha (Calvary)', difficulty: 'easy' },
    
    // MEDIUM - Requires knowledge of specific stories and details
    { id: 21, question: 'Which book contains the Ten Commandments?', answer: 'Exodus', difficulty: 'medium' },
    { id: 22, question: 'Which book contains the Sermon on the Mount?', answer: 'Matthew', difficulty: 'medium' },
    { id: 23, question: 'Which book begins with "In the beginning was the Word"?', answer: 'John (Gospel of John)', difficulty: 'medium' },
    { id: 24, question: 'Who was known for his wisdom and built the first Temple?', answer: 'Solomon', difficulty: 'medium' },
    { id: 25, question: 'Who was the strongest man whose strength came from his hair?', answer: 'Samson', difficulty: 'medium' },
    { id: 26, question: 'Who was thrown into a den of lions?', answer: 'Daniel', difficulty: 'medium' },
    { id: 27, question: 'What were the walls of which city destroyed when Joshua\'s trumpets sounded?', answer: 'Jericho', difficulty: 'medium' },
    { id: 28, question: 'Who interpreted dreams for Pharaoh in Egypt?', answer: 'Joseph', difficulty: 'medium' },
    { id: 29, question: 'Who defeated the prophets of Baal on Mount Carmel?', answer: 'Elijah', difficulty: 'medium' },
    { id: 30, question: 'Who walked on water with Jesus?', answer: 'Peter', difficulty: 'medium' },
    { id: 31, question: 'In which garden did Jesus pray before his arrest?', answer: 'Garden of Gethsemane', difficulty: 'medium' },
    { id: 32, question: 'Where did Jesus perform his first miracle?', answer: 'Cana (Wedding at Cana)', difficulty: 'medium' },
    { id: 33, question: 'Who was raised from the dead by Jesus?', answer: 'Lazarus', difficulty: 'medium' },
    { id: 34, question: 'On which mountain did Moses receive the Ten Commandments?', answer: 'Mount Sinai', difficulty: 'medium' },
    { id: 35, question: 'In which parable does a son return home after wasting his inheritance?', answer: 'The Prodigal Son', difficulty: 'medium' },
    { id: 36, question: 'In which parable does a man help an injured traveler?', answer: 'The Good Samaritan', difficulty: 'medium' },
    { id: 37, question: 'How many plagues did God send to Egypt?', answer: 'Ten (10)', difficulty: 'medium' },
    { id: 38, question: 'How many days and nights did it rain during the flood?', answer: 'Forty (40)', difficulty: 'medium' },
    { id: 39, question: 'In which sea did Jesus walk on water?', answer: 'Sea of Galilee', difficulty: 'medium' },
    { id: 40, question: 'Who was the foster father of Jesus?', answer: 'Joseph', difficulty: 'medium' },
    { id: 41, question: 'On what day did Jesus rise from the dead?', answer: 'Easter Sunday (Third day)', difficulty: 'medium' },
    { id: 42, question: 'Which book contains the psalms and hymns?', answer: 'Psalms', difficulty: 'medium' },
    { id: 43, question: 'Which book tells the story of Ruth and Naomi?', answer: 'Ruth', difficulty: 'medium' },
    { id: 44, question: 'What are the first five books of the Bible called?', answer: 'The Pentateuch (or Torah)', difficulty: 'medium' },
    { id: 45, question: 'Who was the first king of Israel?', answer: 'Saul', difficulty: 'medium' },
    { id: 46, question: 'Which prophet was taken up to heaven in a whirlwind?', answer: 'Elijah', difficulty: 'medium' },
    { id: 47, question: 'Who was the tax collector that Jesus called to be a disciple?', answer: 'Matthew (Levi)', difficulty: 'medium' },
    { id: 48, question: 'Which disciple doubted Jesus\'s resurrection until he saw him?', answer: 'Thomas', difficulty: 'medium' },
    { id: 49, question: 'Who wrote most of the New Testament epistles?', answer: 'Paul (Saul of Tarsus)', difficulty: 'medium' },
    { id: 50, question: 'What was the name of the queen who visited Solomon?', answer: 'Queen of Sheba', difficulty: 'medium' },
    
    // HARD - Deep knowledge, specific details, lesser-known stories
    { id: 51, question: 'Which book contains the story of Job\'s suffering?', answer: 'Job', difficulty: 'hard' },
    { id: 52, question: 'Which book contains the proverbs of Solomon?', answer: 'Proverbs', difficulty: 'hard' },
    { id: 53, question: 'In which city did the Tower of Babel stand?', answer: 'Babylon', difficulty: 'hard' },
    { id: 54, question: 'Which commandment says to honor your father and mother?', answer: 'The Fifth Commandment', difficulty: 'hard' },
    { id: 55, question: 'Which commandment forbids murder?', answer: 'The Sixth Commandment', difficulty: 'hard' },
    { id: 56, question: 'Which commandment tells us to keep the Sabbath day holy?', answer: 'The Fourth Commandment', difficulty: 'hard' },
    { id: 57, question: 'Which commandment forbids coveting?', answer: 'The Tenth Commandment', difficulty: 'hard' },
    { id: 58, question: 'What is the first of the Ten Commandments?', answer: 'You shall have no other gods before me', difficulty: 'hard' },
    { id: 59, question: 'How many books are in the New Testament?', answer: 'Twenty-seven (27)', difficulty: 'hard' },
    { id: 60, question: 'How many books are in the Old Testament (Protestant)?', answer: 'Thirty-nine (39)', difficulty: 'hard' },
    { id: 61, question: 'In which parable does a shepherd leave 99 sheep to find one?', answer: 'The Lost Sheep', difficulty: 'hard' },
    { id: 62, question: 'In which parable does a man build his house on rock versus sand?', answer: 'The Wise and Foolish Builders', difficulty: 'hard' },
    { id: 63, question: 'In which parable does a sower scatter seeds on different grounds?', answer: 'The Parable of the Sower', difficulty: 'hard' },
    { id: 64, question: 'On which mount did Jesus deliver the Sermon on the Mount?', answer: 'Mount of Beatitudes', difficulty: 'hard' },
    { id: 65, question: 'Who was the high priest who questioned Jesus?', answer: 'Caiaphas', difficulty: 'hard' },
    { id: 66, question: 'Which king ordered the slaughter of infants in Bethlehem?', answer: 'Herod (Herod the Great)', difficulty: 'hard' },
    { id: 67, question: 'Who was the judge who led Israel before Saul became king?', answer: 'Samuel', difficulty: 'hard' },
    { id: 68, question: 'Which woman drove a tent peg through the head of Sisera?', answer: 'Jael', difficulty: 'hard' },
    { id: 69, question: 'Which prophet confronted King David about his sin with Bathsheba?', answer: 'Nathan', difficulty: 'hard' },
    { id: 70, question: 'Who succeeded Moses as leader of Israel?', answer: 'Joshua', difficulty: 'hard' },
    { id: 71, question: 'Which king saw the writing on the wall at his feast?', answer: 'Belshazzar', difficulty: 'hard' },
    { id: 72, question: 'Who was the Roman governor who sentenced Jesus to death?', answer: 'Pontius Pilate', difficulty: 'hard' },
    { id: 73, question: 'Which Old Testament figure never died but was taken to heaven?', answer: 'Enoch (and Elijah)', difficulty: 'hard' },
    { id: 74, question: 'Who was struck dead for lying about their donation to the church?', answer: 'Ananias and Sapphira', difficulty: 'hard' },
    { id: 75, question: 'Which book of the Bible is a love poem?', answer: 'Song of Solomon (Song of Songs)', difficulty: 'hard' },
    { id: 76, question: 'Who was the brother of Moses and first high priest?', answer: 'Aaron', difficulty: 'hard' },
    { id: 77, question: 'Which judge killed 600 Philistines with an ox goad?', answer: 'Shamgar', difficulty: 'hard' },
    { id: 78, question: 'Who was the mother of John the Baptist?', answer: 'Elizabeth', difficulty: 'hard' },
    { id: 79, question: 'Which prophet was told to marry a prostitute as a symbol?', answer: 'Hosea', difficulty: 'hard' },
    { id: 80, question: 'On which island was John exiled when he wrote Revelation?', answer: 'Patmos', difficulty: 'hard' },
    { id: 81, question: 'Which king had a dream of a statue made of different metals?', answer: 'Nebuchadnezzar', difficulty: 'hard' },
    { id: 82, question: 'Who was the cupbearer to the king who rebuilt Jerusalem\'s walls?', answer: 'Nehemiah', difficulty: 'hard' },
    { id: 83, question: 'Which book tells of a Jewish woman who became queen of Persia?', answer: 'Esther', difficulty: 'hard' },
    { id: 84, question: 'Who was the father-in-law of Moses?', answer: 'Jethro (Reuel)', difficulty: 'hard' },
    { id: 85, question: 'Which prophet was fed by ravens?', answer: 'Elijah', difficulty: 'hard' },
  ]
};

export default bible;
