// Famous Operas Flash Cards (Enhanced with Difficulty Levels)
export const famousOperas = {
  id: 'famous-operas',
  name: 'Famous Operas',
  description: 'Learn famous operas and their composers',
  category: 'Arts & Culture',
  cards: [
    // EASY - Most famous operas
    { id: 1, question: 'The Magic Flute', answer: 'Wolfgang Amadeus Mozart', difficulty: 'easy' },
    { id: 2, question: 'The Marriage of Figaro', answer: 'Wolfgang Amadeus Mozart', difficulty: 'easy' },
    { id: 3, question: 'Don Giovanni', answer: 'Wolfgang Amadeus Mozart', difficulty: 'easy' },
    { id: 4, question: 'Carmen', answer: 'Georges Bizet', difficulty: 'easy' },
    { id: 5, question: 'La Traviata', answer: 'Giuseppe Verdi', difficulty: 'easy' },
    { id: 6, question: 'Rigoletto', answer: 'Giuseppe Verdi', difficulty: 'easy' },
    { id: 7, question: 'Aida', answer: 'Giuseppe Verdi', difficulty: 'easy' },
    { id: 8, question: 'La Bohème', answer: 'Giacomo Puccini', difficulty: 'easy' },
    { id: 9, question: 'Tosca', answer: 'Giacomo Puccini', difficulty: 'easy' },
    { id: 10, question: 'Madama Butterfly', answer: 'Giacomo Puccini', difficulty: 'easy' },
    { id: 11, question: 'Turandot', answer: 'Giacomo Puccini', difficulty: 'easy' },
    { id: 12, question: 'The Barber of Seville', answer: 'Gioachino Rossini', difficulty: 'easy' },
    { id: 13, question: 'Fidelio', answer: 'Ludwig van Beethoven', difficulty: 'easy' },
    { id: 14, question: 'Porgy and Bess', answer: 'George Gershwin', difficulty: 'easy' },
    { id: 15, question: 'Faust', answer: 'Charles Gounod', difficulty: 'easy' },
    
    // MEDIUM - Well-known operas requiring more knowledge
    { id: 16, question: 'The Ring Cycle (Der Ring des Nibelungen)', answer: 'Richard Wagner', difficulty: 'medium' },
    { id: 17, question: 'Tristan und Isolde', answer: 'Richard Wagner', difficulty: 'medium' },
    { id: 18, question: 'Die Walküre', answer: 'Richard Wagner', difficulty: 'medium' },
    { id: 19, question: 'Parsifal', answer: 'Richard Wagner', difficulty: 'medium' },
    { id: 20, question: 'Boris Godunov', answer: 'Modest Mussorgsky', difficulty: 'medium' },
    { id: 21, question: 'Eugene Onegin', answer: 'Pyotr Ilyich Tchaikovsky', difficulty: 'medium' },
    { id: 22, question: 'The Queen of Spades', answer: 'Pyotr Ilyich Tchaikovsky', difficulty: 'medium' },
    { id: 23, question: 'Pagliacci', answer: 'Ruggero Leoncavallo', difficulty: 'medium' },
    { id: 24, question: 'Cavalleria Rusticana', answer: 'Pietro Mascagni', difficulty: 'medium' },
    { id: 25, question: 'Norma', answer: 'Vincenzo Bellini', difficulty: 'medium' },
    { id: 26, question: 'Lucia di Lammermoor', answer: 'Gaetano Donizetti', difficulty: 'medium' },
    { id: 27, question: 'The Elixir of Love', answer: 'Gaetano Donizetti', difficulty: 'medium' },
    { id: 28, question: 'Salome', answer: 'Richard Strauss', difficulty: 'medium' },
    { id: 29, question: 'Der Rosenkavalier', answer: 'Richard Strauss', difficulty: 'medium' },
    { id: 30, question: 'Elektra', answer: 'Richard Strauss', difficulty: 'medium' },
    { id: 31, question: 'Samson and Delilah', answer: 'Camille Saint-Saëns', difficulty: 'medium' },
    { id: 32, question: 'Les Contes d\'Hoffmann (The Tales of Hoffmann)', answer: 'Jacques Offenbach', difficulty: 'medium' },
    { id: 33, question: 'Hansel and Gretel', answer: 'Engelbert Humperdinck', difficulty: 'medium' },
    { id: 34, question: 'Peter Grimes', answer: 'Benjamin Britten', difficulty: 'medium' },
    { id: 35, question: 'Romeo and Juliet', answer: 'Charles Gounod', difficulty: 'medium' },
    { id: 36, question: 'Il Trovatore', answer: 'Giuseppe Verdi', difficulty: 'medium' },
    { id: 37, question: 'Nabucco', answer: 'Giuseppe Verdi', difficulty: 'medium' },
    { id: 38, question: 'La Gioconda', answer: 'Amilcare Ponchielli', difficulty: 'medium' },
    { id: 39, question: 'Andrea Chénier', answer: 'Umberto Giordano', difficulty: 'medium' },
    { id: 40, question: 'Manon', answer: 'Jules Massenet', difficulty: 'medium' },
    
    // HARD - More obscure operas
    { id: 41, question: 'Wozzeck', answer: 'Alban Berg', difficulty: 'hard' },
    { id: 42, question: 'Lulu', answer: 'Alban Berg', difficulty: 'hard' },
    { id: 43, question: 'Orfeo ed Euridice', answer: 'Christoph Willibald Gluck', difficulty: 'hard' },
    { id: 44, question: 'Dido and Aeneas', answer: 'Henry Purcell', difficulty: 'hard' },
    { id: 45, question: 'The Bartered Bride', answer: 'Bedřich Smetana', difficulty: 'hard' },
    { id: 46, question: 'I Puritani', answer: 'Vincenzo Bellini', difficulty: 'hard' },
    { id: 47, question: 'Don Pasquale', answer: 'Gaetano Donizetti', difficulty: 'hard' },
    { id: 48, question: 'La Sonnambula', answer: 'Vincenzo Bellini', difficulty: 'hard' },
    { id: 49, question: 'L\'italiana in Algeri', answer: 'Gioachino Rossini', difficulty: 'hard' },
    { id: 50, question: 'William Tell', answer: 'Gioachino Rossini', difficulty: 'hard' },
    { id: 51, question: 'Tannhäuser', answer: 'Richard Wagner', difficulty: 'hard' },
    { id: 52, question: 'Lohengrin', answer: 'Richard Wagner', difficulty: 'hard' },
    { id: 53, question: 'The Flying Dutchman', answer: 'Richard Wagner', difficulty: 'hard' },
    { id: 54, question: 'Ariadne auf Naxos', answer: 'Richard Strauss', difficulty: 'hard' },
    { id: 55, question: 'Capriccio', answer: 'Richard Strauss', difficulty: 'hard' },
    { id: 56, question: 'Jenůfa', answer: 'Leoš Janáček', difficulty: 'hard' },
    { id: 57, question: 'Katya Kabanova', answer: 'Leoš Janáček', difficulty: 'hard' },
    { id: 58, question: 'The Makropulos Case', answer: 'Leoš Janáček', difficulty: 'hard' },
    { id: 59, question: 'Duke Bluebeard\'s Castle', answer: 'Béla Bartók', difficulty: 'hard' },
    { id: 60, question: 'Moses und Aron', answer: 'Arnold Schoenberg', difficulty: 'hard' },
  ]
};

export default famousOperas;
