// Classic Novels and Authors Flash Cards (Enhanced with Difficulty Levels)
export const famousNovels = {
  id: 'famous-novels',
  name: 'Classic Novels & Authors',
  description: 'Learn classic novels and their authors',
  category: 'Arts & Culture',
  cards: [
    // EASY - Most famous novels taught in schools
    { id: 1, question: 'Pride and Prejudice', answer: 'Jane Austen', difficulty: 'easy' },
    { id: 2, question: 'To Kill a Mockingbird', answer: 'Harper Lee', difficulty: 'easy' },
    { id: 3, question: '1984', answer: 'George Orwell', difficulty: 'easy' },
    { id: 4, question: 'Animal Farm', answer: 'George Orwell', difficulty: 'easy' },
    { id: 5, question: 'The Great Gatsby', answer: 'F. Scott Fitzgerald', difficulty: 'easy' },
    { id: 6, question: 'Moby-Dick', answer: 'Herman Melville', difficulty: 'easy' },
    { id: 7, question: 'The Catcher in the Rye', answer: 'J.D. Salinger', difficulty: 'easy' },
    { id: 8, question: 'Lord of the Flies', answer: 'William Golding', difficulty: 'easy' },
    { id: 9, question: 'Brave New World', answer: 'Aldous Huxley', difficulty: 'easy' },
    { id: 10, question: 'Fahrenheit 451', answer: 'Ray Bradbury', difficulty: 'easy' },
    { id: 11, question: 'The Adventures of Huckleberry Finn', answer: 'Mark Twain', difficulty: 'easy' },
    { id: 12, question: 'The Adventures of Tom Sawyer', answer: 'Mark Twain', difficulty: 'easy' },
    { id: 13, question: 'Jane Eyre', answer: 'Charlotte Brontë', difficulty: 'easy' },
    { id: 14, question: 'Wuthering Heights', answer: 'Emily Brontë', difficulty: 'easy' },
    { id: 15, question: 'Great Expectations', answer: 'Charles Dickens', difficulty: 'easy' },
    { id: 16, question: 'A Tale of Two Cities', answer: 'Charles Dickens', difficulty: 'easy' },
    { id: 17, question: 'Oliver Twist', answer: 'Charles Dickens', difficulty: 'easy' },
    { id: 18, question: 'Frankenstein', answer: 'Mary Shelley', difficulty: 'easy' },
    { id: 19, question: 'Dracula', answer: 'Bram Stoker', difficulty: 'easy' },
    { id: 20, question: 'The Scarlet Letter', answer: 'Nathaniel Hawthorne', difficulty: 'easy' },
    { id: 21, question: 'The Odyssey', answer: 'Homer', difficulty: 'easy' },
    { id: 22, question: 'The Iliad', answer: 'Homer', difficulty: 'easy' },
    { id: 23, question: 'The Lord of the Rings', answer: 'J.R.R. Tolkien', difficulty: 'easy' },
    { id: 24, question: 'The Hobbit', answer: 'J.R.R. Tolkien', difficulty: 'easy' },
    { id: 25, question: 'Harry Potter and the Philosopher\'s Stone', answer: 'J.K. Rowling', difficulty: 'easy' },
    { id: 26, question: 'The Chronicles of Narnia', answer: 'C.S. Lewis', difficulty: 'easy' },
    { id: 27, question: 'Alice\'s Adventures in Wonderland', answer: 'Lewis Carroll', difficulty: 'easy' },
    { id: 28, question: 'Gone with the Wind', answer: 'Margaret Mitchell', difficulty: 'easy' },
    { id: 29, question: 'Don Quixote', answer: 'Miguel de Cervantes', difficulty: 'easy' },
    { id: 30, question: 'Les Misérables', answer: 'Victor Hugo', difficulty: 'easy' },
    
    // MEDIUM - Well-known but require more literary knowledge
    { id: 31, question: 'War and Peace', answer: 'Leo Tolstoy', difficulty: 'medium' },
    { id: 32, question: 'Anna Karenina', answer: 'Leo Tolstoy', difficulty: 'medium' },
    { id: 33, question: 'Crime and Punishment', answer: 'Fyodor Dostoevsky', difficulty: 'medium' },
    { id: 34, question: 'The Brothers Karamazov', answer: 'Fyodor Dostoevsky', difficulty: 'medium' },
    { id: 35, question: 'David Copperfield', answer: 'Charles Dickens', difficulty: 'medium' },
    { id: 36, question: 'The Grapes of Wrath', answer: 'John Steinbeck', difficulty: 'medium' },
    { id: 37, question: 'Of Mice and Men', answer: 'John Steinbeck', difficulty: 'medium' },
    { id: 38, question: 'East of Eden', answer: 'John Steinbeck', difficulty: 'medium' },
    { id: 39, question: 'The Old Man and the Sea', answer: 'Ernest Hemingway', difficulty: 'medium' },
    { id: 40, question: 'A Farewell to Arms', answer: 'Ernest Hemingway', difficulty: 'medium' },
    { id: 41, question: 'For Whom the Bell Tolls', answer: 'Ernest Hemingway', difficulty: 'medium' },
    { id: 42, question: 'The Sun Also Rises', answer: 'Ernest Hemingway', difficulty: 'medium' },
    { id: 43, question: 'The Sound and the Fury', answer: 'William Faulkner', difficulty: 'medium' },
    { id: 44, question: 'As I Lay Dying', answer: 'William Faulkner', difficulty: 'medium' },
    { id: 45, question: 'One Hundred Years of Solitude', answer: 'Gabriel García Márquez', difficulty: 'medium' },
    { id: 46, question: 'Love in the Time of Cholera', answer: 'Gabriel García Márquez', difficulty: 'medium' },
    { id: 47, question: 'The Hunchback of Notre-Dame', answer: 'Victor Hugo', difficulty: 'medium' },
    { id: 48, question: 'The Count of Monte Cristo', answer: 'Alexandre Dumas', difficulty: 'medium' },
    { id: 49, question: 'The Three Musketeers', answer: 'Alexandre Dumas', difficulty: 'medium' },
    { id: 50, question: 'Madame Bovary', answer: 'Gustave Flaubert', difficulty: 'medium' },
    { id: 51, question: 'The Picture of Dorian Gray', answer: 'Oscar Wilde', difficulty: 'medium' },
    { id: 52, question: 'Heart of Darkness', answer: 'Joseph Conrad', difficulty: 'medium' },
    { id: 53, question: 'Catch-22', answer: 'Joseph Heller', difficulty: 'medium' },
    { id: 54, question: 'Slaughterhouse-Five', answer: 'Kurt Vonnegut', difficulty: 'medium' },
    { id: 55, question: 'The Color Purple', answer: 'Alice Walker', difficulty: 'medium' },
    { id: 56, question: 'Uncle Tom\'s Cabin', answer: 'Harriet Beecher Stowe', difficulty: 'medium' },
    { id: 57, question: 'Treasure Island', answer: 'Robert Louis Stevenson', difficulty: 'medium' },
    { id: 58, question: 'The Strange Case of Dr Jekyll and Mr Hyde', answer: 'Robert Louis Stevenson', difficulty: 'medium' },
    { id: 59, question: 'Twenty Thousand Leagues Under the Sea', answer: 'Jules Verne', difficulty: 'medium' },
    { id: 60, question: 'Around the World in Eighty Days', answer: 'Jules Verne', difficulty: 'medium' },
    
    // HARD - More obscure or challenging works
    { id: 61, question: 'Ulysses', answer: 'James Joyce', difficulty: 'hard' },
    { id: 62, question: 'A Portrait of the Artist as a Young Man', answer: 'James Joyce', difficulty: 'hard' },
    { id: 63, question: 'Mrs. Dalloway', answer: 'Virginia Woolf', difficulty: 'hard' },
    { id: 64, question: 'To the Lighthouse', answer: 'Virginia Woolf', difficulty: 'hard' },
    { id: 65, question: 'Lolita', answer: 'Vladimir Nabokov', difficulty: 'hard' },
    { id: 66, question: 'The Metamorphosis', answer: 'Franz Kafka', difficulty: 'hard' },
    { id: 67, question: 'The Trial', answer: 'Franz Kafka', difficulty: 'hard' },
    { id: 68, question: 'The Stranger (L\'Étranger)', answer: 'Albert Camus', difficulty: 'hard' },
    { id: 69, question: 'The Plague', answer: 'Albert Camus', difficulty: 'hard' },
    { id: 70, question: 'Siddhartha', answer: 'Hermann Hesse', difficulty: 'hard' },
    { id: 71, question: 'The Glass Bead Game', answer: 'Hermann Hesse', difficulty: 'hard' },
    { id: 72, question: 'The House of the Seven Gables', answer: 'Nathaniel Hawthorne', difficulty: 'hard' },
    { id: 73, question: 'The Importance of Being Earnest', answer: 'Oscar Wilde', difficulty: 'hard' },
    { id: 74, question: 'The Divine Comedy', answer: 'Dante Alighieri', difficulty: 'hard' },
    { id: 75, question: 'Paradise Lost', answer: 'John Milton', difficulty: 'hard' },
    { id: 76, question: 'Gulliver\'s Travels', answer: 'Jonathan Swift', difficulty: 'hard' },
    { id: 77, question: 'Robinson Crusoe', answer: 'Daniel Defoe', difficulty: 'hard' },
    { id: 78, question: 'The Time Machine', answer: 'H.G. Wells', difficulty: 'hard' },
    { id: 79, question: 'The War of the Worlds', answer: 'H.G. Wells', difficulty: 'hard' },
    { id: 80, question: 'Lord Jim', answer: 'Joseph Conrad', difficulty: 'hard' },
    { id: 81, question: 'Infinite Jest', answer: 'David Foster Wallace', difficulty: 'hard' },
    { id: 82, question: 'Gravity\'s Rainbow', answer: 'Thomas Pynchon', difficulty: 'hard' },
    { id: 83, question: 'The Recognitions', answer: 'William Gaddis', difficulty: 'hard' },
    { id: 84, question: 'Middlemarch', answer: 'George Eliot', difficulty: 'hard' },
    { id: 85, question: 'Vanity Fair', answer: 'William Makepeace Thackeray', difficulty: 'hard' },
  ]
};

export default famousNovels;
