// Historic Events by Date Flash Cards (Enhanced with Difficulty Levels)
export const historicEvents = {
  id: 'historic-events',
  name: 'Historic Events by Date',
  description: 'Learn major historical events and their dates',
  category: 'History',
  cards: [
    // EASY - Most famous/well-known events
    { id: 1, question: 'Columbus reaches the Americas', answer: '1492', difficulty: 'easy' },
    { id: 2, question: 'American Declaration of Independence', answer: '1776', difficulty: 'easy' },
    { id: 3, question: 'Storming of the Bastille (French Revolution begins)', answer: '1789', difficulty: 'easy' },
    { id: 4, question: 'American Civil War begins', answer: '1861', difficulty: 'easy' },
    { id: 5, question: 'American Civil War ends', answer: '1865', difficulty: 'easy' },
    { id: 6, question: 'Assassination of Abraham Lincoln', answer: '1865', difficulty: 'easy' },
    { id: 7, question: 'Sinking of the Titanic', answer: '1912', difficulty: 'easy' },
    { id: 8, question: 'World War I begins', answer: '1914', difficulty: 'easy' },
    { id: 9, question: 'World War I ends', answer: '1918', difficulty: 'easy' },
    { id: 10, question: 'Stock Market Crash (Great Depression begins)', answer: '1929', difficulty: 'easy' },
    { id: 11, question: 'World War II begins', answer: '1939', difficulty: 'easy' },
    { id: 12, question: 'Pearl Harbor attack', answer: '1941', difficulty: 'easy' },
    { id: 13, question: 'D-Day (Normandy invasion)', answer: '1944', difficulty: 'easy' },
    { id: 14, question: 'Atomic bombs dropped on Hiroshima and Nagasaki', answer: '1945', difficulty: 'easy' },
    { id: 15, question: 'World War II ends', answer: '1945', difficulty: 'easy' },
    { id: 16, question: 'JFK assassination', answer: '1963', difficulty: 'easy' },
    { id: 17, question: 'Moon landing (Apollo 11)', answer: '1969', difficulty: 'easy' },
    { id: 18, question: 'Berlin Wall falls', answer: '1989', difficulty: 'easy' },
    { id: 19, question: 'September 11 attacks', answer: '2001', difficulty: 'easy' },
    { id: 20, question: 'Barack Obama elected (first African American president)', answer: '2008', difficulty: 'easy' },
    
    // MEDIUM - Well-known but require more specific knowledge
    { id: 21, question: 'Signing of the Magna Carta', answer: '1215', difficulty: 'medium' },
    { id: 22, question: 'Fall of Constantinople', answer: '1453', difficulty: 'medium' },
    { id: 23, question: 'Martin Luther posts 95 Theses (Protestant Reformation begins)', answer: '1517', difficulty: 'medium' },
    { id: 24, question: 'Mayflower arrives at Plymouth Rock', answer: '1620', difficulty: 'medium' },
    { id: 25, question: 'Napoleon crowned Emperor', answer: '1804', difficulty: 'medium' },
    { id: 26, question: 'Battle of Waterloo', answer: '1815', difficulty: 'medium' },
    { id: 27, question: 'Origin of Species published by Darwin', answer: '1859', difficulty: 'medium' },
    { id: 28, question: 'Emancipation Proclamation', answer: '1863', difficulty: 'medium' },
    { id: 29, question: 'Unification of Germany', answer: '1871', difficulty: 'medium' },
    { id: 30, question: 'Wright Brothers first flight', answer: '1903', difficulty: 'medium' },
    { id: 31, question: 'Russian Revolution', answer: '1917', difficulty: 'medium' },
    { id: 32, question: 'Women gain right to vote in US (19th Amendment)', answer: '1920', difficulty: 'medium' },
    { id: 33, question: 'Hitler becomes Chancellor of Germany', answer: '1933', difficulty: 'medium' },
    { id: 34, question: 'United Nations founded', answer: '1945', difficulty: 'medium' },
    { id: 35, question: 'India gains independence', answer: '1947', difficulty: 'medium' },
    { id: 36, question: 'State of Israel established', answer: '1948', difficulty: 'medium' },
    { id: 37, question: 'NATO formed', answer: '1949', difficulty: 'medium' },
    { id: 38, question: 'Korean War begins', answer: '1950', difficulty: 'medium' },
    { id: 39, question: 'DNA structure discovered', answer: '1953', difficulty: 'medium' },
    { id: 40, question: 'Brown v. Board of Education decision', answer: '1954', difficulty: 'medium' },
    { id: 41, question: 'Rosa Parks refuses to give up bus seat', answer: '1955', difficulty: 'medium' },
    { id: 42, question: 'Sputnik launched (Space Age begins)', answer: '1957', difficulty: 'medium' },
    { id: 43, question: 'Cuban Revolution (Castro takes power)', answer: '1959', difficulty: 'medium' },
    { id: 44, question: 'Berlin Wall constructed', answer: '1961', difficulty: 'medium' },
    { id: 45, question: 'Cuban Missile Crisis', answer: '1962', difficulty: 'medium' },
    { id: 46, question: 'Civil Rights Act passed', answer: '1964', difficulty: 'medium' },
    { id: 47, question: 'Vietnam War escalates (US combat troops)', answer: '1965', difficulty: 'medium' },
    { id: 48, question: 'MLK Jr. assassination', answer: '1968', difficulty: 'medium' },
    { id: 49, question: 'Watergate scandal breaks', answer: '1972', difficulty: 'medium' },
    { id: 50, question: 'Vietnam War ends', answer: '1975', difficulty: 'medium' },
    { id: 51, question: 'Soviet Union dissolves', answer: '1991', difficulty: 'medium' },
    
    // HARD - Less commonly known dates
    { id: 52, question: 'Spanish Armada defeated', answer: '1588', difficulty: 'hard' },
    { id: 53, question: 'English Civil War begins', answer: '1642', difficulty: 'hard' },
    { id: 54, question: 'Great Fire of London', answer: '1666', difficulty: 'hard' },
    { id: 55, question: 'Glorious Revolution in England', answer: '1688', difficulty: 'hard' },
    { id: 56, question: 'Monroe Doctrine announced', answer: '1823', difficulty: 'hard' },
    { id: 57, question: 'Texas independence from Mexico', answer: '1836', difficulty: 'hard' },
    { id: 58, question: 'Communist Manifesto published', answer: '1848', difficulty: 'hard' },
    { id: 59, question: 'California Gold Rush begins', answer: '1849', difficulty: 'hard' },
    { id: 60, question: 'Crimean War begins', answer: '1853', difficulty: 'hard' },
    { id: 61, question: 'Invention of the telephone by Bell', answer: '1876', difficulty: 'hard' },
    { id: 62, question: 'Edison invents the light bulb', answer: '1879', difficulty: 'hard' },
    { id: 63, question: 'Statue of Liberty dedicated', answer: '1886', difficulty: 'hard' },
    { id: 64, question: 'Spanish-American War', answer: '1898', difficulty: 'hard' },
    { id: 65, question: 'San Francisco Earthquake', answer: '1906', difficulty: 'hard' },
    { id: 66, question: 'Panama Canal opens', answer: '1914', difficulty: 'hard' },
    { id: 67, question: 'Treaty of Versailles signed', answer: '1919', difficulty: 'hard' },
    { id: 68, question: 'Spanish Civil War begins', answer: '1936', difficulty: 'hard' },
    { id: 69, question: 'Iranian Revolution', answer: '1979', difficulty: 'hard' },
    { id: 70, question: 'Tiananmen Square protests', answer: '1989', difficulty: 'hard' },
  ]
};

export default historicEvents;
