// Greek & Roman Mythology Flash Cards (Enhanced with Difficulty Levels)
export const mythology = {
  id: 'mythology',
  name: 'Greek & Roman Mythology',
  description: 'Learn gods, goddesses, heroes, and myths from ancient Greece and Rome',
  category: 'Arts & Culture',
  cards: [
    // EASY - Most famous gods, heroes, and stories
    { id: 1, question: 'Who is the Greek king of the gods?', answer: 'Zeus', difficulty: 'easy' },
    { id: 2, question: 'What is the Roman name for Zeus?', answer: 'Jupiter', difficulty: 'easy' },
    { id: 3, question: 'Who is the Greek god of the sea?', answer: 'Poseidon', difficulty: 'easy' },
    { id: 4, question: 'What is the Roman name for Poseidon?', answer: 'Neptune', difficulty: 'easy' },
    { id: 5, question: 'Who is the Greek god of the underworld?', answer: 'Hades', difficulty: 'easy' },
    { id: 6, question: 'Who completed the Twelve Labors?', answer: 'Hercules (Heracles)', difficulty: 'easy' },
    { id: 7, question: 'Who killed the Minotaur in the labyrinth?', answer: 'Theseus', difficulty: 'easy' },
    { id: 8, question: 'Who defeated Medusa by looking at her reflection?', answer: 'Perseus', difficulty: 'easy' },
    { id: 9, question: 'Who flew too close to the sun with wax wings?', answer: 'Icarus', difficulty: 'easy' },
    { id: 10, question: 'Who was the Greek hero with a vulnerable heel?', answer: 'Achilles', difficulty: 'easy' },
    { id: 11, question: 'Who opened a box releasing all evils into the world?', answer: 'Pandora', difficulty: 'easy' },
    { id: 12, question: 'Who is the Greek goddess of wisdom?', answer: 'Athena', difficulty: 'easy' },
    { id: 13, question: 'Who is the Greek goddess of love and beauty?', answer: 'Aphrodite', difficulty: 'easy' },
    { id: 14, question: 'What creature is half-man, half-bull?', answer: 'Minotaur', difficulty: 'easy' },
    { id: 15, question: 'What monster has snakes for hair?', answer: 'Medusa (Gorgon)', difficulty: 'easy' },
    { id: 16, question: 'What winged horse sprang from Medusa\'s blood?', answer: 'Pegasus', difficulty: 'easy' },
    { id: 17, question: 'Who devised the Trojan Horse?', answer: 'Odysseus', difficulty: 'easy' },
    { id: 18, question: 'Which war lasted ten years and involved a wooden horse?', answer: 'The Trojan War', difficulty: 'easy' },
    { id: 19, question: 'Who is the Greek god of war?', answer: 'Ares', difficulty: 'easy' },
    { id: 20, question: 'Who fell in love with his own reflection?', answer: 'Narcissus', difficulty: 'easy' },
    
    // MEDIUM - More detailed knowledge
    { id: 21, question: 'What is the Roman name for Athena?', answer: 'Minerva', difficulty: 'medium' },
    { id: 22, question: 'What is the Roman name for Aphrodite?', answer: 'Venus', difficulty: 'medium' },
    { id: 23, question: 'What is the Roman name for Ares?', answer: 'Mars', difficulty: 'medium' },
    { id: 24, question: 'What is the Roman name for Hades?', answer: 'Pluto', difficulty: 'medium' },
    { id: 25, question: 'Who is the Greek god of the sun, music, and poetry?', answer: 'Apollo', difficulty: 'medium' },
    { id: 26, question: 'Who is the Greek goddess of the hunt?', answer: 'Artemis', difficulty: 'medium' },
    { id: 27, question: 'Who is the Greek messenger god?', answer: 'Hermes', difficulty: 'medium' },
    { id: 28, question: 'Who is the Greek god of wine?', answer: 'Dionysus', difficulty: 'medium' },
    { id: 29, question: 'Who is the Greek god of fire and metalworking?', answer: 'Hephaestus', difficulty: 'medium' },
    { id: 30, question: 'Who is the Greek goddess of agriculture?', answer: 'Demeter', difficulty: 'medium' },
    { id: 31, question: 'What creature is half-man, half-horse?', answer: 'Centaur', difficulty: 'medium' },
    { id: 32, question: 'What creature guards the underworld with three heads?', answer: 'Cerberus', difficulty: 'medium' },
    { id: 33, question: 'What bird rises from its own ashes?', answer: 'Phoenix', difficulty: 'medium' },
    { id: 34, question: 'Who sailed with the Argonauts to find the Golden Fleece?', answer: 'Jason', difficulty: 'medium' },
    { id: 35, question: 'Who killed his father and married his mother?', answer: 'Oedipus', difficulty: 'medium' },
    { id: 36, question: 'Which three-headed dog did Hercules capture?', answer: 'Cerberus', difficulty: 'medium' },
    { id: 37, question: 'What was Hercules\' first labor?', answer: 'Slay the Nemean Lion', difficulty: 'medium' },
    { id: 38, question: 'Which multi-headed monster did Hercules fight?', answer: 'The Lernaean Hydra', difficulty: 'medium' },
    { id: 39, question: 'Which stables did Hercules clean in one day?', answer: 'The Augean Stables', difficulty: 'medium' },
    { id: 40, question: 'Who was chained to a rock and had his liver eaten daily by an eagle?', answer: 'Prometheus', difficulty: 'medium' },
    { id: 41, question: 'Who created the labyrinth for the Minotaur?', answer: 'Daedalus', difficulty: 'medium' },
    { id: 42, question: 'Who was abducted by Hades to become queen of the underworld?', answer: 'Persephone', difficulty: 'medium' },
    { id: 43, question: 'What did King Midas turn to gold with his touch?', answer: 'Everything (including his daughter)', difficulty: 'medium' },
    { id: 44, question: 'Who lost his wife Eurydice by looking back in the underworld?', answer: 'Orpheus', difficulty: 'medium' },
    { id: 45, question: 'Who was the most beautiful woman whose abduction caused the Trojan War?', answer: 'Helen of Troy', difficulty: 'medium' },
    { id: 46, question: 'Which Trojan prince abducted Helen?', answer: 'Paris', difficulty: 'medium' },
    { id: 47, question: 'What is the Roman name for Artemis?', answer: 'Diana', difficulty: 'medium' },
    { id: 48, question: 'What is the Roman name for Hermes?', answer: 'Mercury', difficulty: 'medium' },
    { id: 49, question: 'What is the Roman name for Hera?', answer: 'Juno', difficulty: 'medium' },
    { id: 50, question: 'Who is the Greek queen of the gods?', answer: 'Hera', difficulty: 'medium' },
    
    // HARD - Obscure details and lesser-known myths
    { id: 51, question: 'What is the Roman name for Apollo?', answer: 'Apollo', difficulty: 'hard' },
    { id: 52, question: 'What is the Roman name for Hephaestus?', answer: 'Vulcan', difficulty: 'hard' },
    { id: 53, question: 'What is the Roman name for Demeter?', answer: 'Ceres', difficulty: 'hard' },
    { id: 54, question: 'What is the Roman name for Dionysus?', answer: 'Bacchus', difficulty: 'hard' },
    { id: 55, question: 'What is the Roman name for Persephone?', answer: 'Proserpina', difficulty: 'hard' },
    { id: 56, question: 'Who was turned into a spider by Athena?', answer: 'Arachne', difficulty: 'hard' },
    { id: 57, question: 'Which golden apples did Hercules retrieve?', answer: 'Apples of the Hesperides', difficulty: 'hard' },
    { id: 58, question: 'What fire-breathing monster has a lion\'s head, goat\'s body, and serpent\'s tail?', answer: 'Chimera', difficulty: 'hard' },
    { id: 59, question: 'What creature asked riddles and had a lion\'s body with eagle wings?', answer: 'Sphinx', difficulty: 'hard' },
    { id: 60, question: 'Which goddess\'s apple started the Trojan War?', answer: 'Eris (Discord)', difficulty: 'hard' },
    { id: 61, question: 'Who was the Greek hero who took 10 years to return home after the war?', answer: 'Odysseus', difficulty: 'hard' },
    { id: 62, question: 'Who was the mortal weaver who challenged Athena?', answer: 'Arachne', difficulty: 'hard' },
    { id: 63, question: 'What was the name of Odysseus\'s faithful wife?', answer: 'Penelope', difficulty: 'hard' },
    { id: 64, question: 'Who was the father of Icarus?', answer: 'Daedalus', difficulty: 'hard' },
    { id: 65, question: 'Which goddess sprang fully formed from Zeus\'s head?', answer: 'Athena', difficulty: 'hard' },
    { id: 66, question: 'Who was the twin brother of Artemis?', answer: 'Apollo', difficulty: 'hard' },
    { id: 67, question: 'Who was the ferryman of the dead across the River Styx?', answer: 'Charon', difficulty: 'hard' },
    { id: 68, question: 'What were the nine daughters of Zeus who presided over arts?', answer: 'The Muses', difficulty: 'hard' },
    { id: 69, question: 'Who were the three Fates who controlled destiny?', answer: 'Clotho, Lachesis, and Atropos', difficulty: 'hard' },
    { id: 70, question: 'What was the food of the gods?', answer: 'Ambrosia', difficulty: 'hard' },
    { id: 71, question: 'What was the drink of the gods?', answer: 'Nectar', difficulty: 'hard' },
    { id: 72, question: 'Who was the Greek god of sleep?', answer: 'Hypnos', difficulty: 'hard' },
    { id: 73, question: 'Who was the Greek goddess of victory?', answer: 'Nike', difficulty: 'hard' },
    { id: 74, question: 'Who was the goddess of the rainbow and messenger of the gods?', answer: 'Iris', difficulty: 'hard' },
    { id: 75, question: 'Who were the three sisters who had one eye and one tooth to share?', answer: 'The Graeae', difficulty: 'hard' },
    { id: 76, question: 'Who was the Titan who held up the sky?', answer: 'Atlas', difficulty: 'hard' },
    { id: 77, question: 'Who was punished by being forced to roll a boulder up a hill forever?', answer: 'Sisyphus', difficulty: 'hard' },
    { id: 78, question: 'Who was punished by standing in water that receded when he tried to drink?', answer: 'Tantalus', difficulty: 'hard' },
    { id: 79, question: 'Who was the Greek primordial god of the sky?', answer: 'Uranus', difficulty: 'hard' },
    { id: 80, question: 'Who was the Greek primordial goddess of the earth?', answer: 'Gaia', difficulty: 'hard' },
    { id: 81, question: 'What was the name of Hades\' wife?', answer: 'Persephone', difficulty: 'hard' },
    { id: 82, question: 'Who was the centaur who taught many Greek heroes?', answer: 'Chiron', difficulty: 'hard' },
    { id: 83, question: 'Which Greek hero was dipped in the River Styx as a baby?', answer: 'Achilles', difficulty: 'hard' },
    { id: 84, question: 'Who was the leader of the Argonauts?', answer: 'Jason', difficulty: 'hard' },
    { id: 85, question: 'What was the name of Jason\'s ship?', answer: 'Argo', difficulty: 'hard' },
  ]
};

export default mythology;
