// Shakespeare Flash Cards (Enhanced with Difficulty Levels)
export const shakespeare = {
  id: 'shakespeare',
  name: 'Shakespeare Plays & Characters',
  description: 'Learn Shakespeare\'s plays, characters, and famous quotes',
  category: 'Arts & Culture',
  cards: [
    // EASY Questions - Most famous plays, quotes, and characters
    { id: 1, question: 'In which play does a prince see his father\'s ghost on castle battlements?', answer: 'Hamlet', difficulty: 'easy' },
    { id: 2, question: 'Which play ends with the deaths of two young lovers from rival families?', answer: 'Romeo and Juliet', difficulty: 'easy' },
    { id: 3, question: 'Which play features three witches who prophesy to a Scottish thane?', answer: 'Macbeth', difficulty: 'easy' },
    { id: 4, question: 'In which play is "To be, or not to be" spoken?', answer: 'Hamlet', difficulty: 'easy' },
    { id: 5, question: 'In which play does a queen sleepwalk, trying to wash blood from her hands?', answer: 'Macbeth', difficulty: 'easy' },
    { id: 6, question: 'Which play features a balcony scene between two star-crossed lovers?', answer: 'Romeo and Juliet', difficulty: 'easy' },
    { id: 7, question: 'Which comedy features a play-within-a-play performed by "rude mechanicals"?', answer: 'A Midsummer Night\'s Dream', difficulty: 'easy' },
    { id: 8, question: 'In which comedy is a weaver given the head of a donkey?', answer: 'A Midsummer Night\'s Dream', difficulty: 'easy' },
    { id: 9, question: 'Which is Shakespeare\'s longest play?', answer: 'Hamlet', difficulty: 'easy' },
    { id: 10, question: 'In which play does a prince famously delay avenging his father\'s murder?', answer: 'Hamlet', difficulty: 'easy' },
    { id: 11, question: 'In which play does a moneylender demand a pound of flesh as collateral?', answer: 'The Merchant of Venice', difficulty: 'easy' },
    { id: 12, question: 'Which history play features King Henry\'s famous St. Crispin\'s Day speech?', answer: 'Henry V', difficulty: 'easy' },
    { id: 13, question: 'In which play is "Friends, Romans, countrymen" spoken at a funeral?', answer: 'Julius Caesar', difficulty: 'easy' },
    { id: 14, question: 'Which comedy features lovers fleeing Athens into an enchanted forest?', answer: 'A Midsummer Night\'s Dream', difficulty: 'easy' },
    { id: 15, question: 'Which play features a shipwreck and a case of mistaken twin identities?', answer: 'Twelfth Night', difficulty: 'easy' },
    
    // MEDIUM Questions - Requires knowledge of multiple plays and details
    { id: 16, question: 'In which tragedy does an elderly king divide his kingdom among his daughters?', answer: 'King Lear', difficulty: 'medium' },
    { id: 17, question: 'Which tragedy features a Moorish general deceived by his ensign?', answer: 'Othello', difficulty: 'medium' },
    { id: 18, question: 'Which comedy features two couples engaged in a "merry war" of wits?', answer: 'Much Ado About Nothing', difficulty: 'medium' },
    { id: 19, question: 'In which comedy does a fortune hunter woo a "cursed" woman for her dowry?', answer: 'The Taming of the Shrew', difficulty: 'medium' },
    { id: 20, question: 'Which play features a trial scene where mercy is contrasted with justice?', answer: 'The Merchant of Venice', difficulty: 'medium' },
    { id: 21, question: 'In which play is the line "All the world\'s a stage" spoken by a melancholy lord?', answer: 'As You Like It', difficulty: 'medium' },
    { id: 22, question: 'Which play contains the "quality of mercy" speech delivered in court?', answer: 'The Merchant of Venice', difficulty: 'medium' },
    { id: 23, question: 'Which play opens with "Now is the winter of our discontent"?', answer: 'Richard III', difficulty: 'medium' },
    { id: 24, question: 'In which play do three weird sisters chant "Double, double toil and trouble"?', answer: 'Macbeth', difficulty: 'medium' },
    { id: 25, question: 'Which play opens with "If music be the food of love, play on"?', answer: 'Twelfth Night', difficulty: 'medium' },
    { id: 26, question: 'In which play is a soothsayer ignored when he warns of a specific date?', answer: 'Julius Caesar', difficulty: 'medium' },
    { id: 27, question: 'Which play features a prince who feigns madness after seeing an apparition?', answer: 'Hamlet', difficulty: 'medium' },
    { id: 28, question: 'In which play does a general see a dagger floating in the air?', answer: 'Macbeth', difficulty: 'medium' },
    { id: 29, question: 'Which tragedy features jealousy sparked by a missing handkerchief?', answer: 'Othello', difficulty: 'medium' },
    { id: 30, question: 'In which play does a character curse both feuding families before dying?', answer: 'Romeo and Juliet', difficulty: 'medium' },
    { id: 31, question: 'Which play features a magician who creates a tempest to shipwreck his enemies?', answer: 'The Tempest', difficulty: 'medium' },
    { id: 32, question: 'What is Shakespeare\'s shortest play?', answer: 'The Comedy of Errors', difficulty: 'medium' },
    { id: 33, question: 'Which play is subtitled "What You Will"?', answer: 'Twelfth Night', difficulty: 'medium' },
    { id: 34, question: 'In which history play does a prince frequent taverns with a fat knight?', answer: 'Henry IV', difficulty: 'medium' },
    { id: 35, question: 'Which deformed king famously offers his kingdom for a horse?', answer: 'Richard III', difficulty: 'medium' },
    { id: 36, question: 'In which comedy does a woman disguise herself as a male shepherd?', answer: 'As You Like It', difficulty: 'medium' },
    { id: 37, question: 'Which play features an Egyptian queen who kills herself with an asp?', answer: 'Antony and Cleopatra', difficulty: 'medium' },
    { id: 38, question: 'In which play does a prince contemplate mortality while holding a skull?', answer: 'Hamlet', difficulty: 'medium' },
    { id: 39, question: 'Which tragedy features a king cast out into a storm by his daughters?', answer: 'King Lear', difficulty: 'medium' },
    { id: 40, question: 'Which play features a dying king\'s speech about "this sceptered isle"?', answer: 'Richard II', difficulty: 'medium' },
    
    // HARD Questions - Deep knowledge, obscure details, lesser-known plays
    { id: 41, question: 'Which Roman tragedy features a father cooking his enemies in a pie?', answer: 'Titus Andronicus', difficulty: 'hard' },
    { id: 42, question: 'In which comedy do young lords vow to avoid women for three years of study?', answer: 'Love\'s Labour\'s Lost', difficulty: 'hard' },
    { id: 43, question: 'Which play features a misanthrope who retreats to a cave?', answer: 'Timon of Athens', difficulty: 'hard' },
    { id: 44, question: 'In which play does a jealous king accuse his wife of adultery with his best friend?', answer: 'The Winter\'s Tale', difficulty: 'hard' },
    { id: 45, question: 'Which play is set during the Trojan War but focuses on Greek infighting?', answer: 'Troilus and Cressida', difficulty: 'hard' },
    { id: 46, question: 'In which play does a woman present her disguised self as a statue?', answer: 'The Winter\'s Tale', difficulty: 'hard' },
    { id: 47, question: 'Which play features a savage who curses his master in borrowed language?', answer: 'The Tempest', difficulty: 'hard' },
    { id: 48, question: 'Which comedy features two sets of identical twins separated at birth?', answer: 'The Comedy of Errors', difficulty: 'hard' },
    { id: 49, question: 'In which romance does a husband wager on his wife\'s virtue?', answer: 'Cymbeline', difficulty: 'hard' },
    { id: 50, question: 'Which play features a duke who disguises himself as a friar to test his deputy?', answer: 'Measure for Measure', difficulty: 'hard' },
    { id: 51, question: 'In which comedy does a woman pursue an unwilling count to fulfill her dead father\'s cure?', answer: 'All\'s Well That Ends Well', difficulty: 'hard' },
    { id: 52, question: 'Which play features a rogue peddler who sells ballads and picks pockets?', answer: 'The Winter\'s Tale', difficulty: 'hard' },
    { id: 53, question: 'In which tragedy does a general\'s mother plead to save Rome from his revenge?', answer: 'Coriolanus', difficulty: 'hard' },
    { id: 54, question: 'Which play ends with a queen applying a snake to her breast?', answer: 'Antony and Cleopatra', difficulty: 'hard' },
    { id: 55, question: 'In which comedy does a boastful soldier get exposed as a coward?', answer: 'All\'s Well That Ends Well', difficulty: 'hard' },
    { id: 56, question: 'Which play features two sisters competing for suitors, with the younger locked away?', answer: 'The Taming of the Shrew', difficulty: 'hard' },
    { id: 57, question: 'In which play does a deputy proposition a novice nun?', answer: 'Measure for Measure', difficulty: 'hard' },
    { id: 58, question: 'Which play features a princess raised by shepherds who doesn\'t know her true identity?', answer: 'The Winter\'s Tale', difficulty: 'hard' },
    { id: 59, question: 'In which comedy does a shipwrecked twin believe their sibling drowned?', answer: 'Twelfth Night', difficulty: 'hard' },
    { id: 60, question: 'Which comedy features an exiled duke living contentedly in the forest?', answer: 'As You Like It', difficulty: 'hard' },
    { id: 61, question: 'In which play does one friend attempt to steal another\'s beloved?', answer: 'The Two Gentlemen of Verona', difficulty: 'hard' },
    { id: 62, question: 'Which romance features a prince searching for his wife and daughter across the Mediterranean?', answer: 'Pericles, Prince of Tyre', difficulty: 'hard' },
    { id: 63, question: 'In which play does a Roman general\'s lieutenant defect and die of remorse?', answer: 'Antony and Cleopatra', difficulty: 'hard' },
    { id: 64, question: 'Which tragedy features a general who seeks refuge with his enemy?', answer: 'Coriolanus', difficulty: 'hard' },
    { id: 65, question: 'In which revenge tragedy is a woman\'s tongue cut out?', answer: 'Titus Andronicus', difficulty: 'hard' },
    { id: 66, question: 'Which comedy features a Spanish braggart composing elaborate love letters?', answer: 'Love\'s Labour\'s Lost', difficulty: 'hard' },
    { id: 67, question: 'In which romance does a king become convinced a statue of his dead wife is moving?', answer: 'The Winter\'s Tale', difficulty: 'hard' },
    { id: 68, question: 'Which tragedy features a lieutenant wrongly suspected of an affair?', answer: 'Othello', difficulty: 'hard' },
    { id: 69, question: 'In which play does a ghost appear at a banquet visible only to one person?', answer: 'Macbeth', difficulty: 'hard' },
    { id: 70, question: 'Which tragedy features a son who disguises himself as a mad beggar?', answer: 'King Lear', difficulty: 'hard' },
    { id: 71, question: 'In which play is a woman initially infatuated with someone else before meeting the hero?', answer: 'Romeo and Juliet', difficulty: 'hard' },
    { id: 72, question: 'Which history play features a Welsh captain who argues about military honor?', answer: 'Henry V', difficulty: 'hard' },
    { id: 73, question: 'In which play does a spirit serve a magician before being freed?', answer: 'The Tempest', difficulty: 'hard' },
    { id: 74, question: 'Which tragedy ends with a Norwegian prince taking over a Danish kingdom?', answer: 'Hamlet', difficulty: 'hard' },
    { id: 75, question: 'In which play does a man see visions urging him toward murder?', answer: 'Macbeth', difficulty: 'hard' },
  ]
};

export default shakespeare;
